# Generated by Django 3.2.7 on 2022-01-11 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tier', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'подписка', 'verbose_name_plural': 'подписки'},
        ),
        migrations.AlterModelOptions(
            name='tier',
            options={'verbose_name': 'Создать стоимость подписки', 'verbose_name_plural': 'Создать стоимость подписки'},
        ),
        migrations.AlterField(
            model_name='tier',
            name='can_message',
            field=models.BooleanField(default=False, verbose_name='Может ли пользователь отправить вам сообщение'),
        ),
    ]
