# Generated by Django 3.2.7 on 2022-01-11 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookmark',
            options={'verbose_name': 'Закладка', 'verbose_name_plural': 'Закладки'},
        ),
        migrations.AlterModelOptions(
            name='postfilecontent',
            options={'verbose_name': 'Опубликовать содержимое файла', 'verbose_name_plural': 'Опубликовать содержимое файла'},
        ),
    ]
